### ISSUE TITLE
Dont work on my synology since 8th january

### ISSUE THREAD

**Issue by BimmerZug** [liofal/streamlink#11] opened 2024-01-17 17:43 UTC
Since 01/08/2024, the recording is no longer saved. The logs are all in order. I have already deleted the image and created a new container. Unfortunately without success. I use a Synology DS218+ with the version: 7.2.1-69057 Update 4. I installed the update today. With version: 7.2-64570 Update 3 I apparently had no problems. I have also updated my Twitch auth tokens. Is this a known issue?

![image](https://github.com/liofal/streamlink/assets/156940794/e25e7203-c744-49db-80da-39bdbb85ecda)

![image](https://github.com/liofal/streamlink/assets/156940794/0530d02e-de50-4642-8048-35804913e804)

**Comment by liofal** [comment] 2024-01-18 06:13
you probably have same issue, as #10 

have you tried rollback to a previous tag, I will look into it furthermore so far I cannot reproduce, but I dont doubt that it's not working for you guys.

are you using the compose to kickstart it?

**Comment by liofal** [comment] 2024-01-18 06:44
can you try enforce version to 2.0.2?
image: liofal/streamlink:2.0.2

**Comment by liofal** [comment] 2024-01-18 08:39
found it, should be fixed now, sorry about that...

**Comment by BimmerZug** [comment] 2024-01-18 21:34
Thank you for your quick response and support. I have deleted everything. I have now used version 2.0.3 for the image. Unfortunately without improvement. The log is again without errors. Perhaps the following line in the log is interesting?

2024/01/18 20:14:31 stdout [cli][info] Writing output to

Here are my current settings.

![image](https://github.com/liofal/streamlink/assets/156940794/f38d48d9-72ed-447f-92c7-5e24bf99c491)

![image](https://github.com/liofal/streamlink/assets/156940794/b0f5927e-33c8-4fd0-a223-f5e54c0b5381)

**Comment by liofal** [comment] 2024-01-19 08:20
sure, no worries, you must change you volume path within your container to:
/app/download instead of /download

**Comment by BimmerZug** [comment] 2024-01-22 20:13
Thank you, that has solved my problem. Should I now switch back to the latest channel?

**Comment by liofal** [comment] 2024-01-24 06:58
thanks for the update, and sorry for inconvenience for this broken change.
yes you can now switch back to the latest channel... in the future I will migrate ghcr.io might bring another breaking change for you, so be mindful :)

**Closed as completed by liofal** 2024-01-24 06:58 UTC
